[package]
name = "lumina_core"
version = "0.1.0"
edition = "2021"

[dependencies]
blake2 = { workspace = true }

[dev-dependencies]
proptest = "1.0"

[workspace]
members = [
    "contracts/config_manager",
]

default-members = [
    "contracts/config_manager",
]

resolver = "2"

[workspace.dependencies]
soroban-sdk = { version = "26.1.0" }
blake2 = "0.10"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
