[package]
name = "lumina_core"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "src/consensus",
    "contracts/vesting_contracts",
    "contracts/grant_contracts",
    "contracts/staking_contract",
    "contracts/vesting_status_nft",
    "contracts/vesting_vault",
    "contracts/deposit_to_yield_adapter",
    "contracts/insurance_treasury",
]

default-members = [
    "contracts/vesting_contracts",
    "contracts/grant_contracts",
    "contracts/staking_contract",
    "contracts/vesting_status_nft",
    "contracts/vesting_vault",
    "contracts/deposit_to_yield_adapter",
    "contracts/insurance_treasury",
]

resolver = "2"

[workspace.dependencies]
soroban-sdk = { version = "20.5.0" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
